In [1]:
import numpy as np
from scipy.linalg import lu
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [2]:
A = np.random.randn(5,5)
A

array([[-1.468, -0.095,  1.459, -0.287,  2.569],
       [ 0.821,  0.262,  0.548, -0.253,  2.245],
       [ 1.77 ,  1.426, -0.94 , -0.084, -0.852],
       [-0.141,  0.79 ,  1.539, -0.065, -0.743],
       [ 0.171, -0.743, -1.045,  0.308,  0.378]])

#### Function for LU decomposition using partial pivoting

In [3]:
def ozkan_lu(M):
    m = M.shape[0]
    U=M.copy()
    L=np.eye(m)
    P= np.eye(m)
    for k in range(m-1):
        i = np.argmax(np.abs(U[k:,k]))+k # Find the max in the column

        temp  = U[i,k:].copy() # pivot U
        U[i,k:]= U[k,k:]
        U[k,k:] = temp

        P[[k,i]]=P[[i,k]] # pivot P
        
        temp  = L[k,:k].copy() # pivot L
        L[k,:k]= L[i,:k]
        L[i,:k] = temp 

        for j in range(k+1,m):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:m]=U[j,k:m]-L[j,k]*U[k,k:m]
    return P,L,U

In [4]:
P,L,U = ozkan_lu(A)
print(L)
print(U)

[[ 1.     0.     0.     0.     0.   ]
 [-0.829  1.     0.     0.     0.   ]
 [ 0.464 -0.368  1.     0.     0.   ]
 [-0.08   0.831  0.729  1.     0.   ]
 [ 0.096 -0.81  -0.328 -0.179  1.   ]]
[[ 1.77   1.426 -0.94  -0.084 -0.852]
 [ 0.     1.088  0.679 -0.356  1.862]
 [ 0.     0.     1.234 -0.345  3.325]
 [ 0.     0.     0.     0.476 -4.783]
 [ 0.     0.     0.     0.     2.204]]


#### Check to make sure that PA=LU

In [5]:
print(A)
print(np.dot(P,A))
print(np.dot(L,U))

[[-1.468 -0.095  1.459 -0.287  2.569]
 [ 0.821  0.262  0.548 -0.253  2.245]
 [ 1.77   1.426 -0.94  -0.084 -0.852]
 [-0.141  0.79   1.539 -0.065 -0.743]
 [ 0.171 -0.743 -1.045  0.308  0.378]]
[[ 1.77   1.426 -0.94  -0.084 -0.852]
 [-1.468 -0.095  1.459 -0.287  2.569]
 [ 0.821  0.262  0.548 -0.253  2.245]
 [-0.141  0.79   1.539 -0.065 -0.743]
 [ 0.171 -0.743 -1.045  0.308  0.378]]
[[ 1.77   1.426 -0.94  -0.084 -0.852]
 [-1.468 -0.095  1.459 -0.287  2.569]
 [ 0.821  0.262  0.548 -0.253  2.245]
 [-0.141  0.79   1.539 -0.065 -0.743]
 [ 0.171 -0.743 -1.045  0.308  0.378]]
